version: '3'
services:
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    volumes:
      - ./ui/:/usr/src/app
      - ./protos/:/usr/src/protos
      - ./node_modules/:/usr/src/node_modules
    ports:
      - "4200:4200"
  node-server:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api/:/server
      - ./protos/:/protos
    ports:
      - "3000:3000"
      - "5000:5000"
  envoy:
    build:
      context: ./envoy
      dockerfile: ./Dockerfile`
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    links:
      - node-server
